name: Render OpenSCAD PNGs

on:
  workflow_dispatch:

  push:
    paths:
      - "cad/v1.0/**"
      - ".github/workflows/render-openscad.yml"

permissions:
  contents: write

jobs:
  render:
    uses: brainboxemb/brainboxemb.github.actions/.github/workflows/openscad-render.yml@main
    with:
      projects: |
        cad/v1.0|out/v1.0/png|hub75-display-case

      image_size: "2560,1440"
      changed_only: true

      watermark_text: ${{ vars.RENDER_WATERMARK_TEXT }}

      git_user_name: ${{ vars.GIT_USER_NAME }}
      git_user_email: ${{ vars.GIT_USER_EMAIL }}

      commit_message: "Update OpenSCAD documentation renders"
